<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-Q23M30KF" failures="1" tests="8" name="test.LamMoiKhuyenMai" time="131.623" errors="0" timestamp="2024-04-13T17:33:07 ICT" skipped="0">
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai" time="23.515"/>
  <system-out/>
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai1" time="9.503"/>
  <system-out/>
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai2" time="12.104"/>
  <system-out/>
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai3" time="13.724">
    <failure message="expected [Mã khuyến mãi quá dài] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Mã khuyến mãi quá dài] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at test.LamMoiKhuyenMai.insertKhuyenmai3(LamMoiKhuyenMai.java:194)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- insertKhuyenmai3 -->
  <system-out/>
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai4" time="37.221"/>
  <system-out/>
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai5" time="13.668"/>
  <system-out/>
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai6" time="9.745"/>
  <system-out/>
  <testcase classname="test.LamMoiKhuyenMai" name="insertKhuyenmai7" time="12.143"/>
  <system-out/>
</testsuite> <!-- test.LamMoiKhuyenMai -->
